add params to log extraction script

diff --git a/spatial-ld/sim/profiling/extract-logs-from-running-jobs b/spatial-ld/sim/profiling/extract-logs-from-running-jobs
--- a/spatial-ld/sim/profiling/extract-logs-from-running-jobs
+++ b/spatial-ld/sim/profiling/extract-logs-from-running-jobs
@@ -1,10 +1,25 @@
 #!/bin/bash
-set -eou pipefail
+set -eo pipefail
+
+if [[ -z "$1" ]]; then
+    echo "ERROR: missing input params csv"
+    echo
+    echo "usage: extract-logs-from-running-jobs <params_csv> <job_number>"
+    exit 1
+fi
+if [[ -z "$2" ]]; then
+    echo "ERROR: missing job number"
+    echo
+    echo "usage: extract-logs-from-running-jobs <params_csv> <job_number>"
+    exit 1
+fi
+PARAMS_CSV="$1"
+JOB_NUMBER="$2"
 
 i=0
 while read l; do
     d=logs/out/$(cut -f1,2 -d, <<<"$l"| sed -e's/,/_/g')
-    mkdir -p $d
-    condor_tail -maxbytes 100000 1584725.$i > $d/outerr.log
+    mkdir -p "$d"
+    condor_tail -maxbytes 100000 "${JOB_NUMBER}.$i" > "$d/outerr.log"
     ((i++))
-done < params.csv
+done < "$PARAMS_CSV"
